name: Install Splunk on EC2

on:
  workflow_dispatch:  # This makes it manually triggerable from the GitHub Actions UI

jobs:
  install_splunk:
    runs-on: ubuntu-latest

    steps:
      # Checkout code (if necessary)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install SSH client
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # Set private key for SSH connection to EC2 instance
      - name: Set SSH private key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > AAA.pem
          chmod 400 AAA.pem
        shell: bash

      # Install Splunk on EC2 instance
      - name: Install Splunk on EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}  # Fetch EC2 public IP from GitHub secrets
          PRIVATE_KEY_PATH: AAA.pem
        run: |
          # Ensure the private key file is readable
          chmod 400 $PRIVATE_KEY_PATH

          # Install Splunk using SSH and bash inline script
          ssh -v -o StrictHostKeyChecking=no -i $PRIVATE_KEY_PATH ec2-user@$EC2_PUBLIC_IP << 'EOF'
            # Switch to root user
            sudo su -

            # Update system
            yum update -y
            yum install -y wget

            # Download Splunk RPM (replace with your version if necessary)
            SPLUNK_URL="https://download.splunk.com/products/splunk/releases/9.4.1/linux/splunk-9.4.1-7cc4e2d6f12a-linux-x86_64.rpm"
            SPLUNK_RPM="splunk-9.4.1-7cc4e2d6f12a-linux-x86_64.rpm"

            # Download and install Splunk RPM
            wget -O $SPLUNK_RPM $SPLUNK_URL
            rpm -ivh $SPLUNK_RPM

            # Start Splunk and accept the license
            /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt

            # Enable Splunk to start on boot
            /opt/splunk/bin/splunk enable boot-start

            # Create admin user and set password
            /opt/splunk/bin/splunk add user admin -password 'Plmokn@!13579' -role admin

            # Restart Splunk to apply changes
            /opt/splunk/bin/splunk restart

            echo "Splunk installation complete."
          EOF

      # Output success message
      - name: Output Success Message
        run: |
          echo "Splunk has been successfully installed on EC2 instance at ${EC2_PUBLIC_IP}."
