name: Install Splunk on EC2

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request events targeting the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install_splunk:
    runs-on: ubuntu-latest

    steps:
      # Checkout code (if necessary)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install SSH client
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # Get the public IP of the EC2 instance from GitHub secrets
      - name: Set EC2 Public IP from secrets
        run: echo "EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }}" >> $GITHUB_ENV

      # Set private key for SSH connection to EC2 instance
      - name: Set SSH private key
        run: echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        shell: bash

      - name: Install Splunk on EC2
        env:
          PRIVATE_KEY_PATH: private_key.pem
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          # Ensure the private key file is readable
          chmod 600 $PRIVATE_KEY_PATH

          # Install Splunk on EC2 using SSH and bash inline script
          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY_PATH ubuntu@$EC2_PUBLIC_IP << 'EOF'
            # Update system and install wget
            sudo apt-get update -y
            sudo apt-get install -y wget

            # Download Splunk (replace with your version if necessary)
            SPLUNK_URL="https://download.splunk.com/products/splunk/releases/9.4.1/linux/splunk-9.4.1-e3bdab203ac8-linux-amd64.deb"
            SPLUNK_DEB="splunk-9.4.1-e3bdab203ac8-linux-amd64.deb"

            # Download and install Splunk
            wget -O $SPLUNK_DEB $SPLUNK_URL
            sudo dpkg -i $SPLUNK_DEB

            # Start Splunk and accept the license
            sudo /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt

            # Enable Splunk to start on boot
            sudo /opt/splunk/bin/splunk enable boot-start

            # Create admin user and set password
            sudo /opt/splunk/bin/splunk add user admin -password 'Plmokn@!13579' -role admin

            # Restart Splunk to apply changes
            sudo /opt/splunk/bin/splunk restart

            echo "Splunk installation complete."
          EOF

      # Output success message
      - name: Output Success Message
        run: echo "Splunk has been successfully installed on EC2 instance at ${EC2_PUBLIC_IP}."
